{"sid": "97982b4199a54ab89163d2353d400dc8", "uid": null, "qid": "92157d9f83aa41c6b667bd1bc68b0dd2", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [92157d9f83aa41c6b667bd1bc68b0dd2]\nTraceback (most recent call last):\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 385, in connect_check_health\n    sock = self.retry.call_with_retry(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/retry.py\", line 87, in call_with_retry\n    return do()\n           ^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 386, in <lambda>\n    lambda: self._connect(), lambda error: self.disconnect(error)\n            ^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 797, in _connect\n    raise err\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 781, in _connect\n    sock.connect(socket_address)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/home/psyduck/openfabric-test/app/main.py\", line 90, in execute\n    llm_response = chain_with_history.invoke(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 5431, in invoke\n    return self.bound.invoke(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 5431, in invoke\n    return self.bound.invoke(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 3045, in invoke\n    input_ = context.run(step.invoke, input_, config, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 5431, in invoke\n    return self.bound.invoke(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/passthrough.py\", line 511, in invoke\n    return self._call_with_config(self._invoke, input, config, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 1940, in _call_with_config\n    context.run(\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/config.py\", line 428, in call_func_with_variable_args\n    return func(input, **kwargs)  # type: ignore[call-arg]\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/passthrough.py\", line 497, in _invoke\n    **self.mapper.invoke(\n      ^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 3774, in invoke\n    output = {key: future.result() for key, future in zip(steps, futures)}\n                   ^^^^^^^^^^^^^^^\n  File \"/home/psyduck/anaconda3/lib/python3.12/concurrent/futures/_base.py\", line 456, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/anaconda3/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/psyduck/anaconda3/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 3758, in _invoke_step\n    return context.run(\n           ^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 5431, in invoke\n    return self.bound.invoke(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 4772, in invoke\n    return self._call_with_config(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 1940, in _call_with_config\n    context.run(\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/config.py\", line 428, in call_func_with_variable_args\n    return func(input, **kwargs)  # type: ignore[call-arg]\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py\", line 4630, in _invoke\n    output = call_func_with_variable_args(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/config.py\", line 428, in call_func_with_variable_args\n    return func(input, **kwargs)  # type: ignore[call-arg]\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_core/runnables/history.py\", line 518, in _enter_history\n    messages = hist.messages.copy()\n               ^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/langchain_community/chat_message_histories/redis.py\", line 100, in messages\n    _items = self.redis_client.lrange(self.key, 0, -1)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/commands/core.py\", line 2718, in lrange\n    return self.execute_command(\"LRANGE\", name, start, end, keys=[name])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/client.py\", line 623, in execute_command\n    return self._execute_command(*args, **options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/client.py\", line 629, in _execute_command\n    conn = self.connection or pool.get_connection()\n                              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/utils.py\", line 191, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 1530, in get_connection\n    connection.connect()\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 379, in connect\n    self.connect_check_health(check_health=True)\n  File \"/home/psyduck/.cache/pypoetry/virtualenvs/ai-test-hgYQlvpL-py3.12/lib/python3.12/site-packages/redis/connection.py\", line 391, in connect_check_health\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "created_at": "2025-07-02T21:28:34.147418"}], "status": "FAILED", "created_at": "2025-07-02T21:28:32.877593", "updated_at": "2025-07-02T21:28:34.147446", "finished": true}